FROM node:8
ARG proxy
ARG app_path

WORKDIR /$app_path
COPY package.json .
VOLUME /$app_path/src
VOLUME /$app_path/build
VOLUME /$app_path/config
VOLUME /$app_path/dist

# cache package.json and node_modules to speed up builds
RUN npm config `echo $proxy | sed 's/^$/delete proxy/;s/\(\S\S*\)/set proxy \1/'`
RUN npm install

#COPY . . 

EXPOSE 8080
CMD ["npm","run","build"]
