FROM node:11-slim
ARG proxy
ARG app_path
ARG app_name
ARG app_ver
ENV APP ${APP}
ENV APP_VERSION ${APP_VERSION}

WORKDIR /$app_path
COPY package.json.template .
RUN cat package.json.template | sed "s/<APP>/${app_name}/;s/<VERSION>/${app_ver}/" > package.json
VOLUME /$app_path/src
VOLUME /$app_path/build
VOLUME /$app_path/config


# cache package.json and node_modules to speed up builds
RUN npm config `echo $proxy | sed 's/^$/delete proxy/;s/\(\S\S*\)/set proxy \1/'`
RUN npm i npm@latest -g
RUN npm install --verbose
#RUN npm audit fix --force

#COPY . .

EXPOSE 8080
CMD ["npm","run","dev"]
