FROM node:12-slim
ARG http_proxy
ARG https_proxy
ARG no_proxy
ARG npm_registry
ARG sass_registry
ARG MIRROR_DEBIAN
ARG app_path
ARG app_name
ARG app_ver
ENV APP ${APP}
ENV APP_VERSION ${app_ver}

WORKDIR /$app_path
COPY package.json .babelrc .editorconfig .eslintignore .eslintrc.js ./
VOLUME /$app_path/src
VOLUME /$app_path/build
VOLUME /$app_path/config

# update debian w/proxy & mirror
RUN echo "$http_proxy $no_proxy" && set -x && [ -z "$MIRROR_DEBIAN" ] || \
   sed -i.orig -e "s|http://deb.debian.org\([^[:space:]]*\)|$MIRROR_DEBIAN/debian9|g ; s|http://security.debian.org\([^[:space:]]*\)|$MIRROR_DEBIAN/debian9-security|g" /etc/apt/sources.list
RUN apt-get update

# install git in case of github deps
RUN buildDeps="git" ; \
   apt-get install -qy --no-install-recommends $buildDeps ; \
   git config --global url."https://".insteadOf git://

# use proxy & private npm registry
RUN if [ ! -z "$http_proxy" ] ; then \
        npm config delete proxy; \
        npm config set proxy $http_proxy; \
        npm config set https-proxy $https_proxy ; \
        npm config set no-proxy $no_proxy; \
   fi ; \
   [ -z "$npm_registry" ] || npm config set registry=$npm_registry; \
   [ -z "$sass_registry" ] || npm config set sass_binary_site=$sass_registry; 

RUN npm i npm@latest -g
RUN npm --no-git-tag-version version ${APP_VERSION}
RUN npm install --verbose
RUN npm audit fix #--force

EXPOSE 8080
CMD ["npm","run","dev"]
