version: '3.4'

services:
  public-backend:
    image: ${APP}-public-backend-${EXEC_ENV}:${APP_VERSION}
    build:
      context: ${BACKEND}
      target: ${EXEC_ENV}
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
        MIRROR_DEBIAN: ${MIRROR_DEBIAN}
        app_path: /${APP}
        app_name: ${APP}
        app_ver: ${APP_VERSION}
        port: ${PUBLIC_BACKEND_PORT}
        file_app_version: ${FILE_PUBLIC_BACKEND_APP_VERSION}
        file_dist_app_version: ${FILE_PUBLIC_BACKEND_DIST_APP_VERSION}
        NPM_FIX: ${NPM_FIX}
        NPM_LATEST: ${NPM_LATEST}
        NPM_VERBOSE: ${NPM_VERBOSE}
    container_name: ${APP}-public-backend-${EXEC_ENV}
    ports:
      - ${PUBLIC_BACKEND_PORT}:${PUBLIC_BACKEND_PORT}
    environment:
      - NODE_ENV=${EXEC_ENV}
      - BACKEND_NAME=${BACKEND_NAME}
      - BACKEND_PORT=${PUBLIC_BACKEND_PORT}
      - APP=${APP}
      - APP_VERSION=${APP_VERSION}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PERSIST=${REDIS_PERSIST}
      - ES_URL=${ES_URL}
      - ES_INDEX=${ES_INDEX}
      - IS_UTAC_API_ACTIVATED=${IS_UTAC_API_ACTIVATED}
      - IS_UTAC_MOCK_FOR_BPSA_ACTIVATED=${IS_UTAC_MOCK_FOR_BPSA_ACTIVATED}
      - FAKE_UTAC_URL=${FAKE_UTAC_SCHEME}://${FAKE_UTAC_HOST}:${FAKE_UTAC_PORT}/${FAKE_UTAC_API}
      - UTAC_ID_KEY=${UTAC_ID_KEY}
      - UTAC_URL=${UTAC_URL}
      - UTAC_TIMEOUT=${UTAC_TIMEOUT}
      - UTAC_USERNAME=${UTAC_USERNAME}
      - UTAC_PASSWORD=${UTAC_PASSWORD}
      - HISTOVEC_PFX=${HISTOVEC_PFX}
      - HISTOVEC_PFX_PASSPHRASE=${HISTOVEC_PFX_PASSPHRASE}
      - INES_TOKEN=${INES_TOKEN}
      - UTAC_PEM=${UTAC_PEM}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_TO=${MAIL_TO}
      - PUBLIC_BACKEND=true
      - IS_UTAC_CACHE_IGNORABLE=${IS_UTAC_CACHE_IGNORABLE}
      - PUBLIC_BACKEND_API_UUID=${PUBLIC_BACKEND_API_UUID}
      - USE_PREVIOUS_MONTH_FOR_DATA=${USE_PREVIOUS_MONTH_FOR_DATA}
      - PREVIOUS_MONTH_SHIFT=${PREVIOUS_MONTH_SHIFT}
      - NIVEAU_LOG_A_FORCER=${NIVEAU_LOG_A_FORCER}
    volumes:
      - ${BACKEND}/src:/${APP}/src/
      - ${BACKEND}/dist:/${APP}/dist/
      - /${APP}/node_modules
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PUBLIC_BACKEND_PORT}/${APP}/api/v1/health"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 40s

networks:
  default:
    external:
      name: ${APP}
