##############################################
# WARNING : THIS FILE SHOULDN'T BE TOUCHED   #
#    FOR ENVIRONNEMENT CONFIGURATION         #
# CONFIGURABLE VARIABLES SHOULD BE OVERRIDED #
# IN THE 'artifacts' FILE, AS NOT COMMITTED  #
##############################################

include Makefile

export openstack_url = $(shell echo $$openstack_url )
export openstack_auth_id = $(shell echo $$openstack_auth_id )
export openstack_token = $(shell echo $$openstack_token )


