import routes from "../../../constants/urls.json";

context('Rapport acheteur vehicule cas simple - onglet Situation administrative', () => {
  before(() => {
    cy.intercept('POST', '/public/v1/get_token', { statusCode: 200, fixture: 'token.json' })
    cy.intercept('GET', '/public/v1/report_by_code/**', { statusCode: 200, fixture: '/api/reponseRequeteApiCode200.json' })
    cy.intercept('PUT', '**/buyer/ok', { statusCode: 200 })
    cy.intercept('PUT', '**/administrative-status', { statusCode: 200 })

    // redirection vers la page propriétaire
    cy.visit(routes.url_rapport_acheteur + '?key=b30514dd-f4e8-4036-a102-87d5ca365e66')
    cy.title().should('eq', 'HistoVec - Rapport acheteur')
    cy.wait(500)

    // Onlget Situation administrative selectionné
    cy.get("div[class*='fr-tabs']")
      .find("ul[class*='fr-tabs__list']")
      .find("li[class*='fr-tabs__item']")
      .should('have.length', 7)
      .eq(3)
      .find("button[class*='fr-tabs__tab']")
      .should('have.attr', 'aria-selected', 'false')
      .contains("Situation administrative")
      .click()
      .should('have.attr', 'aria-selected', 'true')
  })
  it("Affichage de l'onglet Situation administrative - Situation administrative", () => {
    // Structure
    cy.get("div[id*='report-tab-content-3']")
      .should("have.class", "fr-tabs__panel fr-tabs__panel--selected")
      .find("div[class='fr-col-12 fr-col-md-6 fr-col-lg-6 fr-col-xl-6']")
      .should('have.length', 2)
      .eq(0)
      .find("div[class*='fr-col-12 fr-pb-2w']")
      .should('have.length', 3)
      .parent()
      .find("h3")
      .should('have.length', 3)
      .parent()
      .parent()
      .find("div[class*='fr-col-12 fr-pb-0 fr-pt-0']")
      .should('have.length', 2)
      .parent()
      .find("div[class*='fr-col-6 fr-col-lg-4 fr-col-xl-4 fr-pb-3w fr-pt-0']")
      .should('have.length', 1)
      .parent()
      .find("div[class*='fr-col-6 fr-col-lg-8 fr-col-xl-8 fr-pb-3w fr-pt-0 fr-text--bleu']")
      .should('have.length', 1)

    cy.get("div[id*='report-tab-content-3']")
      .should("have.class", "fr-tabs__panel fr-tabs__panel--selected")
      .find("div[class='fr-col-12 fr-col-md-6 fr-col-lg-6 fr-col-xl-6']")
      .should('have.length', 2)
      .eq(1)
      .find("div[class*='fr-col-12 fr-pb-2w']")
      .should('have.length', 3)
      .parent()
      .find("h3")
      .should('have.length', 3)
      .parent()
      .parent()
      .find("div[class*='fr-col-12 fr-pb-0 fr-pt-0']")
      .should('have.length', 2)
      .parent()
      .find("div[class*='fr-col-6 fr-col-lg-4 fr-col-xl-4 fr-pb-0 fr-pt-0']")
      .should('have.length', 2)
      .parent()
      .find("div[class*='fr-col-6 fr-col-lg-4 fr-col-xl-4 fr-pb-3w fr-pt-0']")
      .should('have.length', 1)
      .parent()
      .find("div[class*='fr-col-6 fr-col-lg-8 fr-col-xl-8 fr-pb-0 fr-pt-0 fr-text--bleu']")
      .should('have.length', 2)
      .parent()
      .find("div[class*='fr-col-6 fr-col-lg-8 fr-col-xl-8 fr-pb-3w fr-pt-0 fr-text--bleu']")
      .should('have.length', 1)

    // Gages
    cy.get("div[id*='report-tab-content-3']")
      .should("have.class", "fr-tabs__panel fr-tabs__panel--selected")
      .find("div[class='fr-col-12 fr-col-md-6 fr-col-lg-6 fr-col-xl-6']")
      .eq(0)
      .find("div[class*='fr-col-12 fr-pb-2w']")
      .eq(0)
      .find("h3")
      .should('have.length', 1)
      .contains("Gages")
      .find("span")
      .should('have.length', 1)
      .find("a")
      .should('have.length', 1)
      .should("have.class", "fr-link")
      .should('have.attr', 'href', "https://www.service-public.fr/particuliers/vosdroits/F34107")
      .parent()
      .parent()
      .parent()
      .parent()
      .find("div[class='fr-col-12 fr-pb-0 fr-pt-0']")
      .eq(0)
      .find("div[class='fr-text--md']")
      .find("span[class='fr-text--bleu']")
      .contains("NON")

    // Oppositions
    cy.get("div[id*='report-tab-content-3']")
      .should("have.class", "fr-tabs__panel fr-tabs__panel--selected")
      .find("div[class='fr-col-12 fr-col-md-6 fr-col-lg-6 fr-col-xl-6']")
      .eq(0)
      .find("div[class*='fr-col-12 fr-pb-2w']")
      .eq(1)
      .find("h3")
      .should('have.length', 1)
      .contains("Oppositions")
      .find("span")
      .should('have.length', 1)
      .find("a")
      .should('have.length', 1)
      .should("have.class", "fr-link")
      .should('have.attr', 'href', "https://www.service-public.fr/particuliers/vosdroits/F34107")
      .parent()
      .parent()
      .parent()
      .parent()
      .find("div[class='fr-col-12 fr-pb-0 fr-pt-0']")
      .eq(0)
      .find("div[class='fr-text--md']")
      .find("span[class='fr-text--bleu']")
      .contains("NON")

    // Véhicule
    cy.get("div[id*='report-tab-content-3']")
      .should("have.class", "fr-tabs__panel fr-tabs__panel--selected")
      .find("div[class='fr-col-12 fr-col-md-6 fr-col-lg-6 fr-col-xl-6']")
      .eq(0)
      .find("div[class*='fr-col-12 fr-pb-2w']")
      .eq(2)
      .find("h3")
      .should('have.length', 1)
      .contains("Véhicule")
      .parent()
      .parent()
      .find("div[class*='fr-col-6 fr-col-lg-4 fr-col-xl-4 fr-pb-3w fr-pt-0']")
      .contains("Déclaré volé")
      .parent()
      .find("div[class*='fr-col-6 fr-col-lg-8 fr-col-xl-8 fr-pb-3w fr-pt-0 fr-text--bleu']")
      .contains("NON")

    // Déclarations valant saisie
    cy.get("div[id*='report-tab-content-3']")
      .should("have.class", "fr-tabs__panel fr-tabs__panel--selected")
      .find("div[class='fr-col-12 fr-col-md-6 fr-col-lg-6 fr-col-xl-6']")
      .eq(1)
      .find("div[class*='fr-col-12 fr-pb-2w']")
      .eq(0)
      .find("h3")
      .should('have.length', 1)
      .contains("Déclarations valant saisie")
      .parent()
      .parent()
      .find("div[class='fr-col-12 fr-pb-0 fr-pt-0']")
      .eq(0)
      .find("div[class='fr-text--md']")
      .find("span[class='fr-text--bleu']")
      .contains("NON")

    // Suspensions
    cy.get("div[id*='report-tab-content-3']")
      .should("have.class", "fr-tabs__panel fr-tabs__panel--selected")
      .find("div[class='fr-col-12 fr-col-md-6 fr-col-lg-6 fr-col-xl-6']")
      .eq(1)
      .find("div[class*='fr-col-12 fr-pb-2w']")
      .eq(1)
      .find("h3")
      .should('have.length', 1)
      .contains("Suspensions")
      .parent()
      .parent()
      .find("div[class='fr-col-12 fr-pb-0 fr-pt-0']")
      .eq(1)
      .find("div[class='fr-text--md']")
      .find("span[class='fr-text--bleu']")
      .contains("NON")

    // Certificat d'immatriculation
    cy.get("div[id*='report-tab-content-3']")
      .should("have.class", "fr-tabs__panel fr-tabs__panel--selected")
      .find("div[class='fr-col-12 fr-col-md-6 fr-col-lg-6 fr-col-xl-6']")
      .eq(1)
      .find("div[class*='fr-col-12 fr-pb-2w']")
      .eq(2)
      .find("h3")
      .should('have.length', 1)
      .contains("Certificat d'immatriculation")
      .parent()
      .parent()
      .find("div[class*='fr-col-6 fr-col-lg-4 fr-col-xl-4 fr-pb-0 fr-pt-0']")
      .eq(0)
      .contains("Déclaré volée")
      .parent()
      .find("div[class*='fr-col-6 fr-col-lg-4 fr-col-xl-4 fr-pb-0 fr-pt-0']")
      .eq(1)
      .contains("Déclaré perdue")
      .parent()
      .find("div[class*='fr-col-6 fr-col-lg-4 fr-col-xl-4 fr-pb-3w fr-pt-0']")
      .eq(0)
      .contains("Duplicata")
      .parent()
      .find("div[class*='fr-col-6 fr-col-lg-8 fr-col-xl-8 fr-pb-0 fr-pt-0 fr-text--bleu']")
      .eq(0)
      .contains("NON")
      .parent()
      .find("div[class*='fr-col-6 fr-col-lg-8 fr-col-xl-8 fr-pb-0 fr-pt-0 fr-text--bleu']")
      .eq(1)
      .contains("NON")
      .parent()
      .find("div[class*='fr-col-6 fr-col-lg-8 fr-col-xl-8 fr-pb-3w fr-pt-0 fr-text--bleu']")
      .eq(0)
      .contains("NON")
  })
})
