export const OPERATION_VALUE = {
  CUMUL_OPERATIONS: 'CUMUL_OPERATIONS',
  IMMAT_DIPLO_DEMANDE: 'IMMAT_DIPLO_DEMANDE',
  IMMAT_DIPLO_CONFIRMATION: 'IMMAT_DIPLO_CONFIRMATION',
  IMMAT_DIPLO_INFIRMATION: 'IMMAT_DIPLO_INFIRMATION',
  IMMAT_DIPLO_RETIRER: 'IMMAT_DIPLO_RETIRER',
  IMMAT_DIPLO_PREM_VO_CONF: 'IMMAT_DIPLO_PREM_VO_CONF',
  IMMAT_NORMALE_PREM_ETRANGER: 'IMMAT_NORMALE_PREM_ETRANGER',
  IMMAT_NORMALE_PREM_VO: 'IMMAT_NORMALE_PREM_VO',
  IMMAT_NORMALE: 'IMMAT_NORMALE',
  IMMAT_NORMALE_SOURCE_INCERTAINE: 'IMMAT_NORMALE_SOURCE_INCERTAINE',
  IVN_CARROSSIER_QUALIFIE: 'IVN_CARROSSIER_QUALIFIE',
  IMMAT_WG: 'IMMAT_WG',
  IMMAT_PROVISOIRE: 'IMMAT_PROVISOIRE',
  RENOUV_WG: 'RENOUV_WG',
  PROROG_IMMAT: 'PROROG_IMMAT',
  CHANG_TIT_NORMAL: 'CHANG_TIT_NORMAL',
  CHANG_TIT_PREDEMANDE_INTERNET: 'CHANG_TIT_PREDEMANDE_INTERNET',
  CHANG_TIT_DIPLO: 'CHANG_TIT_DIPLO',
  CHANG_LOC: 'CHANG_LOC',
  MODIFIER_USAGES: 'MODIFIER_USAGES',
  FIN_USAGE_DEMO_VENTE: 'FIN_USAGE_DEMO_VENTE',
  FIN_USAGE_DEMO_FINDEM: 'FIN_USAGE_DEMO_FINDEM',
  PROROG_USAGE: 'PROROG_USAGE',
  ATT_NUM_USURPATION: 'ATT_NUM_USURPATION',
  MODIF_ADRESSE: 'MODIF_ADRESSE',
  MODIF_ADRESSE_DGME: 'MODIF_ADRESSE_DGME',
  MODIF_ADRESSE_LOCATAIRE_PRO: 'MODIF_ADRESSE_LOCATAIRE_PRO',
  MODIF_ETAT_CIVIL: 'MODIF_ETAT_CIVIL',
  REIMMAT_ETRANGER: 'REIMMAT_ETRANGER',
  RETOUR_REIMMAT_ETR: 'RETOUR_REIMMAT_ETR',
  RETRAIT_VOLONTAIRE: 'RETRAIT_VOLONTAIRE',
  REMISE_CIRC_RETRAIT_VOL: 'REMISE_CIRC_RETRAIT_VOL',
  SORTIE_TERRITOIRE: 'SORTIE_TERRITOIRE',
  REMISE_CIRC_SORTIE_TERR: 'REMISE_CIRC_SORTIE_TERR',
  DUPLICATA: 'DUPLICATA',
  DEC_VE: 'DEC_VE',
  PREM_RAP_VE: 'PREM_RAP_VE',
  SEC_RAP_VE: 'SEC_RAP_VE',
  INSCRIPTION_GAGE: 'INSCRIPTION_GAGE',
  CESSION_GAGE: 'CESSION_GAGE',
  RADIATION_GAGE: 'RADIATION_GAGE',
  PROROG_GAGE: 'PROROG_GAGE',
  DECLARATION_DESTRUCTION: 'DECLARATION_DESTRUCTION',
  DESTRUCTION_VEHICULE: 'DESTRUCTION_VEHICULE',
  DECLARATION_ACHAT: 'DECLARATION_ACHAT',
  DECLARATION_CESSION: 'DECLARATION_CESSION',
  DECLARATION_CESSION_DGME: 'DECLARATION_CESSION_DGME',
  INSCRIRE_OTCI: 'INSCRIRE_OTCI',
  LEVER_OTCI: 'LEVER_OTCI',
  INSCRIRE_OPPOSITION: 'INSCRIRE_OPPOSITION',
  LEVER_OPPOSITION: 'LEVER_OPPOSITION',
  INSCRIRE_DVS: 'INSCRIRE_DVS',
  LEVER_DVS: 'LEVER_DVS',
  RENOUV_DVS: 'RENOUV_DVS',
  RELANCE_PROD_DOC: 'RELANCE_PROD_DOC',
  PROD_TITRE_HORS_DUPLICATA: 'PROD_TITRE_HORS_DUPLICATA',
  RESTITUTION_TITRE: 'RESTITUTION_TITRE',
  DECLARATION_PERTE_TITRE: 'DECLARATION_PERTE_TITRE',
  EDITION_CPI: 'EDITION_CPI',
  MODIF_CARAC_TECH: 'MODIF_CARAC_TECH',
  REMISE_LOT_TITRE: 'REMISE_LOT_TITRE',
  REMISE_TITRE_FO: 'REMISE_TITRE_FO',
  REMISE_TITRE_PREF: 'REMISE_TITRE_PREF',
  IMMOBILISATION_VEHICULE: 'IMMOBILISATION_VEHICULE',
  IMMOBILISATION_VEHICULE_ADM: 'IMMOBILISATION_VEHICULE_ADM',
  LEVEE_IMMOBILISATION_VEHICULE: 'LEVEE_IMMOBILISATION_VEHICULE',
  INSCRIRE_MSG_SERVICE: 'INSCRIRE_MSG_SERVICE',
  INCONU_REPRISE: 'INCONU_REPRISE',
  REPRISE_DP7_1993: 'REPRISE_DP7_1993',
  CONVERSION_DOSSIER_FNI: 'CONVERSION_DOSSIER_FNI',
  CORRECTION_DOSSIER: 'CORRECTION_DOSSIER',
  CORRECTION_SIT_ADMIN: 'CORRECTION_SIT_ADMIN',
  CORRECTION_TITULAIRE: 'CORRECTION_TITULAIRE',
  CORRECTION_VEHICULE: 'CORRECTION_VEHICULE',
  CORRECTION_TITRE: 'CORRECTION_TITRE',
  CORRECTION_AUTORISATION: 'CORRECTION_AUTORISATION',
  PROD_DOC: 'PROD_DOC',
  INSCRIRE_OVE: 'INSCRIRE_OVE',
  LEVER_OVE: 'LEVER_OVE',
  MODIF_DROIT_OPPOSITION: 'MODIF_DROIT_OPPOSITION',
  ATTRIBUTION_CODE_CONF: 'ATTRIBUTION_CODE_CONF',
  VEHICULE_REFCNIT_RUBVARIABLES: 'VEHICULE_REFCNIT_RUBVARIABLES',
  VEHICULE_REFCNIT_MENTIONVARIABLE: 'VEHICULE_REFCNIT_MENTIONVARIABLE',
  RECHERCHE_DOSSIERS: 'RECHERCHE_DOSSIERS',
  CONSULT_DOSSIER: 'CONSULT_DOSSIER',
  ANNULATION_OPERATION: 'ANNULATION_OPERATION',
  MAJ_PARAM_FONC: 'MAJ_PARAM_FONC',
  ADMIN_NOMENC: 'ADMIN_NOMENC',
  CREA_COMPT_UTIL: 'CREA_COMPT_UTIL',
  MODIF_COMPT_UTIL: 'MODIF_COMPT_UTIL',
  INVA_COMPT_UTIL: 'INVA_COMPT_UTIL',
  SUSP_REAC_COMPT_UTIL: 'SUSP_REAC_COMPT_UTIL',
  CREA_COMPT_PART: 'CREA_COMPT_PART',
  MODIF_COMPT_PART: 'MODIF_COMPT_PART',
  SUSP_REAC_COMPT_PART: 'SUSP_REAC_COMPT_PART',
  ACTIVATION_COMPT_PART: 'ACTIVATION_COMPT_PART',
  SUSPENSION_COMPT_PART: 'SUSPENSION_COMPT_PART',
  RAD_COMPT_PART: 'RAD_COMPT_PART',
  RETRAIT_COMPT_PART: 'RETRAIT_COMPT_PART',
  RESILIATION_COMPT_PART: 'RESILIATION_COMPT_PART',
  MODIFICATION_NOMBRE_GUICHETS: 'MODIFICATION_NOMBRE_GUICHETS',
  CREA_COMPT_CONC: 'CREA_COMPT_CONC',
  MODIF_COMPT_CONC: 'MODIF_COMPT_CONC',
  INVA_COMPT_CONC: 'INVA_COMPT_CONC',
  ANNULATION: 'ANNULATION',
  MODIF_ADRESSE_CVN: 'MODIF_ADRESSE_CVN',
  CHANG_TIT_NORMAL_CVN: 'CHANG_TIT_NORMAL_CVN',
  CHANG_TIT_DIPLO_CVN: 'CHANG_TIT_DIPLO_CVN',
  CHANG_LOC_CVN: 'CHANG_LOC_CVN',
  PROROG_USAGE_CVN: 'PROROG_USAGE_CVN',
  MODIFIER_USAGES_CVN: 'MODIFIER_USAGES_CVN',
  MODIF_ETAT_CIVIL_CVN: 'MODIF_ETAT_CIVIL_CVN',
  MODIF_CARAC_TECH_CVN: 'MODIF_CARAC_TECH_CVN',
  RENOUV_WG_CVN: 'RENOUV_WG_CVN',
  FIN_USAGE_DEMO_FINDEM_CVN: 'FIN_USAGE_DEMO_FINDEM_CVN',
  FIN_USAGE_DEMO_VENTE_CVN: 'FIN_USAGE_DEMO_VENTE_CVN',
  ATT_NUM_USURPATION_CVN: 'ATT_NUM_USURPATION_CVN',
  ANNULATION_ETATS_ADMINISTRATIFS: 'ANNULATION_ETATS_ADMINISTRATIFS',
  EXECUTION_REQUETE_ANTS: 'EXECUTION_REQUETE_ANTS',
  ANN_PROG_REQUETE_ANTS: 'ANN_PROG_REQUETE_ANTS',
  ENR_PROG_REQUETE_ANTS: 'ENR_PROG_REQUETE_ANTS',
  OUTREPASSER_VOL: 'OUTREPASSER_VOL',
  OUTREPASSER_VIN_DOUBLON: 'OUTREPASSER_VIN_DOUBLON',
  OUTREPASSER_VIN_NON_CONTROLE: 'OUTREPASSER_VIN_NON_CONTROLE',
  OUTREPASSER_OTC_INDISPONIBLE: 'OUTREPASSER_OTC_INDISPONIBLE',
  OUTREPASSER_CT_EXONERATION: 'OUTREPASSER_CT_EXONERATION',
  OUTREPASSER_CT_EXEMPTION: 'OUTREPASSER_CT_EXEMPTION',
  OUTREPASSER_EXONERATION_TAXES: 'OUTREPASSER_EXONERATION_TAXES',
  OUTREPASSER_REFCNIT_RUBVARIABLES: 'OUTREPASSER_REFCNIT_RUBVARIABLES',
  OUTREPASSER_REFCNIT_MENTIONVARIABLE: 'OUTREPASSER_REFCNIT_MENTIONVARIABLE',
  BATCH_VEHICULES_IMPORTES: 'BATCH_VEHICULES_IMPORTES',
  EDIT_ETAT_REGIE: 'EDIT_ETAT_REGIE',
}

export const HISTORIQUE_OPERATION_TYPE = [

{value: OPERATION_VALUE.CUMUL_OPERATIONS, text: 'Cumul de plusieurs actions'},
{value: OPERATION_VALUE.IMMAT_DIPLO_DEMANDE, text: 'Demande d\'immatriculation diplomatique'},
{value: OPERATION_VALUE.IMMAT_DIPLO_CONFIRMATION, text: 'Confirmation d\'une immatriculation diplomatique'},
{value: OPERATION_VALUE.IMMAT_DIPLO_INFIRMATION, text: 'Infirmation d\'une immatriculation diplomatique'},
{value: OPERATION_VALUE.IMMAT_DIPLO_RETIRER, text: 'Retrait d\'une immatriculation diplomatique'},
{value: OPERATION_VALUE.IMMAT_DIPLO_PREM_VO_CONF, text: 'Première immatriculation en série diplomatique d\'un véhicule d\'occasion'},
{value: OPERATION_VALUE.IMMAT_NORMALE_PREM_ETRANGER, text: 'Première immatriculation à l\'étranger'},
{value: OPERATION_VALUE.IMMAT_NORMALE_PREM_VO, text: 'Première immatriculation d\'un véhicule d\'occasion'},
{value: OPERATION_VALUE.IMMAT_NORMALE, text: 'Première immatriculation d\'un véhicule neuf'},
{value: OPERATION_VALUE.IMMAT_NORMALE_SOURCE_INCERTAINE, text: 'Première immatriculation (source incertaine)'},
{value: OPERATION_VALUE.IVN_CARROSSIER_QUALIFIE, text: 'Immatriculation d\'un véhicule neuf avec carrossier qualifié'},
{value: OPERATION_VALUE.IMMAT_WG, text: 'Immatriculation en série W Garage'},
{value: OPERATION_VALUE.IMMAT_PROVISOIRE, text: 'Immatriculation provisoire'},
{value: OPERATION_VALUE.RENOUV_WG, text: 'Renouvellement d\'un W Garage'},
{value: OPERATION_VALUE.PROROG_IMMAT, text: 'Prorogation d\'une immatriculation provisoire'},
{value: OPERATION_VALUE.CHANG_TIT_NORMAL, text: 'Changement de titulaire'},
{value: OPERATION_VALUE.CHANG_TIT_PREDEMANDE_INTERNET, text: 'Changement de titulaire (Pré-demande par Internet)'},
{value: OPERATION_VALUE.CHANG_TIT_DIPLO, text: 'Changement de titulaire en série diplomatique'},
{value: OPERATION_VALUE.CHANG_LOC, text: 'Changement de locataire'},
{value: OPERATION_VALUE.MODIFIER_USAGES, text: 'Modification d\'usage'},
{value: OPERATION_VALUE.FIN_USAGE_DEMO_VENTE, text: 'Fin d\'usage démonstration pour vente du véhicule'},
{value: OPERATION_VALUE.FIN_USAGE_DEMO_FINDEM, text: 'Fin d’usage de démonstration'},
{value: OPERATION_VALUE.PROROG_USAGE, text: 'Prorogation d\'usage temporaire'},
{value: OPERATION_VALUE.ATT_NUM_USURPATION, text: 'Changement d\'immatriculation'},
{value: OPERATION_VALUE.MODIF_ADRESSE, text: 'Modification d\'adresse'},
{value: OPERATION_VALUE.MODIF_ADRESSE_DGME, text: 'Modification d\'adresse (dématérialisée)'},
{value: OPERATION_VALUE.MODIF_ADRESSE_LOCATAIRE_PRO, text: 'Modification d\'adresse du locataire'},
{value: OPERATION_VALUE.MODIF_ETAT_CIVIL, text: 'Modification d\'état civil'},
{value: OPERATION_VALUE.REIMMAT_ETRANGER, text: 'Déclaration de réimmatriculation à l\'étranger'},
{value: OPERATION_VALUE.RETOUR_REIMMAT_ETR, text: 'Remise en circulation suite à réimmatriculation à l\'étranger'},
{value: OPERATION_VALUE.RETRAIT_VOLONTAIRE, text: 'Retrait de la circulation par le propriétaire'},
{value: OPERATION_VALUE.REMISE_CIRC_RETRAIT_VOL, text: 'Remise en circulation suite à retrait volontaire'},
{value: OPERATION_VALUE.SORTIE_TERRITOIRE, text: 'Déclaration de sortie de territoire '},
{value: OPERATION_VALUE.REMISE_CIRC_SORTIE_TERR, text: 'Remise en circulation suite à sortie du territoire'},
{value: OPERATION_VALUE.DUPLICATA, text: 'Duplicata du certificat d\'immatriculation'},
{value: OPERATION_VALUE.DEC_VE, text: 'Procédure de réparation contrôlée'},
{value: OPERATION_VALUE.PREM_RAP_VE, text: 'Premier rapport d\'expert'},
{value: OPERATION_VALUE.SEC_RAP_VE, text: 'Second rapport d\'expert'},
{value: OPERATION_VALUE.INSCRIPTION_GAGE, text: 'Inscription d\'un gage'},
{value: OPERATION_VALUE.CESSION_GAGE, text: 'Cession d\'un gage'},
{value: OPERATION_VALUE.RADIATION_GAGE, text: 'Radiation d\'un gage'},
{value: OPERATION_VALUE.PROROG_GAGE, text: 'Prorogation d\'un gage'},
{value: OPERATION_VALUE.DECLARATION_DESTRUCTION, text: 'Déclaration d\'intention de destruction'},
{value: OPERATION_VALUE.DESTRUCTION_VEHICULE, text: 'Déclaration de destruction physique'},
{value: OPERATION_VALUE.DECLARATION_ACHAT, text: 'Achat ou reprise par un professionnel'},
{value: OPERATION_VALUE.DECLARATION_CESSION, text: 'Cession (vente)'},
{value: OPERATION_VALUE.DECLARATION_CESSION_DGME, text: 'Déclaration de cession (dématérialisée)'},
{value: OPERATION_VALUE.INSCRIRE_OTCI, text: 'Opposition au transfert du certificat d\'immatriculation'},
{value: OPERATION_VALUE.LEVER_OTCI, text: 'Fin d\'opposition au transfert du certificat d\'immatriculation'},
{value: OPERATION_VALUE.INSCRIRE_OPPOSITION, text: 'Inscription d\'une opposition'},
{value: OPERATION_VALUE.LEVER_OPPOSITION, text: 'Levée d\'une opposition'},
{value: OPERATION_VALUE.INSCRIRE_DVS, text: 'Inscription d\'une déclaration valant saisie'},
{value: OPERATION_VALUE.LEVER_DVS, text: 'Levée d\'une déclaration valant saisie'},
{value: OPERATION_VALUE.RENOUV_DVS, text: 'Renouvellement d\'une déclaration valant saisie'},
{value: OPERATION_VALUE.RELANCE_PROD_DOC, text: 'Relance manuelle d\'une production de titre'},
{value: OPERATION_VALUE.PROD_TITRE_HORS_DUPLICATA, text: 'Production d\'un titre hors duplicata'},
{value: OPERATION_VALUE.RESTITUTION_TITRE, text: 'Restitution du titre au titulaire'},
{value: OPERATION_VALUE.DECLARATION_PERTE_TITRE, text: 'Perte du certificat d\'immatriculation'},
{value: OPERATION_VALUE.EDITION_CPI, text: 'Edition d\'un CPI'},
{value: OPERATION_VALUE.MODIF_CARAC_TECH, text: 'Modification des caractéristiques techniques '},
{value: OPERATION_VALUE.REMISE_LOT_TITRE, text: 'Remise d\'un lot de titres'},
{value: OPERATION_VALUE.REMISE_TITRE_FO, text: 'Remise du titre FO'},
{value: OPERATION_VALUE.REMISE_TITRE_PREF, text: 'Remise du titre en préfecture'},
{value: OPERATION_VALUE.IMMOBILISATION_VEHICULE, text: 'Immobilisation du véhicule'},
{value: OPERATION_VALUE.IMMOBILISATION_VEHICULE_ADM, text: 'Immobilisation administrative du véhicule'},
{value: OPERATION_VALUE.LEVEE_IMMOBILISATION_VEHICULE, text: 'Levée de l\'immobilisation du véhicule'},
{value: OPERATION_VALUE.INSCRIRE_MSG_SERVICE, text: 'Inscription d\'un message service'},
{value: OPERATION_VALUE.INCONU_REPRISE, text: 'Reprise inconnue'},
{value: OPERATION_VALUE.REPRISE_DP7_1993, text: 'Reprise DP7'},
{value: OPERATION_VALUE.CONVERSION_DOSSIER_FNI, text: 'Conversion au nouveau format d\'immatriculation'},
{value: OPERATION_VALUE.CORRECTION_DOSSIER, text: 'Correction de dossier'},
{value: OPERATION_VALUE.CORRECTION_SIT_ADMIN, text: 'Correction de la situation administrative'},
{value: OPERATION_VALUE.CORRECTION_TITULAIRE, text: 'Correction des informations du titulaire'},
{value: OPERATION_VALUE.CORRECTION_VEHICULE, text: 'Correction des informations du véhicule'},
{value: OPERATION_VALUE.CORRECTION_TITRE, text: 'Correction de l\'état de remise du titre'},
{value: OPERATION_VALUE.CORRECTION_AUTORISATION, text: 'Correction des informations sur l\'autorisation'},
{value: OPERATION_VALUE.PROD_DOC, text: 'Production de document'},
{value: OPERATION_VALUE.INSCRIRE_OVE, text: 'Opposition dans le cadre de la procédure de réparation contrôlée'},
{value: OPERATION_VALUE.LEVER_OVE, text: 'Levée d\'une opposition véhicule endommagé'},
{value: OPERATION_VALUE.MODIF_DROIT_OPPOSITION, text: 'Modification du droit d\'opposition'},
{value: OPERATION_VALUE.ATTRIBUTION_CODE_CONF, text: 'Attribution d\'un code confidentiel'},
{value: OPERATION_VALUE.VEHICULE_REFCNIT_RUBVARIABLES, text: 'Caractéristiques techniques liées à un CNIT à rubriques variables'},
{value: OPERATION_VALUE.VEHICULE_REFCNIT_MENTIONVARIABLE, text: 'Caractéristiques techniques liées à un CNIT à mentions variables'},
{value: OPERATION_VALUE.RECHERCHE_DOSSIERS, text: 'Recherche de dossiers'},
{value: OPERATION_VALUE.CONSULT_DOSSIER, text: 'Consultation d\'un dossier'},
{value: OPERATION_VALUE.ANNULATION_OPERATION, text: 'Annulation d\'une opération'},
{value: OPERATION_VALUE.MAJ_PARAM_FONC, text: 'Modification des paramètres fonctionnels'},
{value: OPERATION_VALUE.ADMIN_NOMENC, text: 'Administration des nomenclatures'},
{value: OPERATION_VALUE.CREA_COMPT_UTIL, text: 'Création d\'un utilisateur'},
{value: OPERATION_VALUE.MODIF_COMPT_UTIL, text: 'Modification d\'un utilisateur'},
{value: OPERATION_VALUE.INVA_COMPT_UTIL, text: 'Suppression d\'un utilisateur'},
{value: OPERATION_VALUE.SUSP_REAC_COMPT_UTIL, text: 'Activation ou suspension d\'un utilisateur'},
{value: OPERATION_VALUE.CREA_COMPT_PART, text: 'Création d\'un compte partenaire'},
{value: OPERATION_VALUE.MODIF_COMPT_PART, text: 'Modification d\'un compte partenaire'},
{value: OPERATION_VALUE.SUSP_REAC_COMPT_PART, text: 'Activation ou suspension d\'un compte partenaire (antérieure à la V3.0) '},
{value: OPERATION_VALUE.ACTIVATION_COMPT_PART, text: 'Activation d\'un compte partenaire'},
{value: OPERATION_VALUE.SUSPENSION_COMPT_PART, text: 'Suspension d\'un compte partenaire'},
{value: OPERATION_VALUE.RAD_COMPT_PART, text: 'Retrait ou résiliation d\'un compte partenaire (antérieure à la V3.0) '},
{value: OPERATION_VALUE.RETRAIT_COMPT_PART, text: 'Retrait d\'un compte partenaire'},
{value: OPERATION_VALUE.RESILIATION_COMPT_PART, text: 'Resiliation d\'un compte partenaire'},
{value: OPERATION_VALUE.MODIFICATION_NOMBRE_GUICHETS, text: 'Modification du nombre de guichets'},
{value: OPERATION_VALUE.CREA_COMPT_CONC, text: 'Création d\'un concentrateur'},
{value: OPERATION_VALUE.MODIF_COMPT_CONC, text: 'Modification d\'un concentrateur'},
{value: OPERATION_VALUE.INVA_COMPT_CONC, text: 'Retrait d\'un concentrateur'},
{value: OPERATION_VALUE.ANNULATION, text: 'Annulation d\'une opération terminée'},
{value: OPERATION_VALUE.MODIF_ADRESSE_CVN, text: 'Modification d\'adresse avec conversion'},
{value: OPERATION_VALUE.CHANG_TIT_NORMAL_CVN, text: 'Changement de titulaire et conversion au nouveau format d\'immatriculation'},
{value: OPERATION_VALUE.CHANG_TIT_DIPLO_CVN, text: 'Changement de titulaire en série diplomatique avec conversion'},
{value: OPERATION_VALUE.CHANG_LOC_CVN, text: 'Changement de locataire avec conversion'},
{value: OPERATION_VALUE.PROROG_USAGE_CVN, text: 'Prorogation d\'usage temporaire avec conversion'},
{value: OPERATION_VALUE.MODIFIER_USAGES_CVN, text: 'Modification d\'usage avec conversion'},
{value: OPERATION_VALUE.MODIF_ETAT_CIVIL_CVN, text: 'Modification d\'état civil avec conversion'},
{value: OPERATION_VALUE.MODIF_CARAC_TECH_CVN, text: 'Modification des caractéristiques techniques avec conversion'},
{value: OPERATION_VALUE.RENOUV_WG_CVN, text: 'Renouvellement d\'un W Garage avec conversion'},
{value: OPERATION_VALUE.FIN_USAGE_DEMO_FINDEM_CVN, text: 'Fin d\'usage démonstration pour changement d\'affectation avec conversion'},
{value: OPERATION_VALUE.FIN_USAGE_DEMO_VENTE_CVN, text: 'Fin d\'usage démonstration pour vente du véhicule avec conversion'},
{value: OPERATION_VALUE.ATT_NUM_USURPATION_CVN, text: 'Changement d\'immatriculation avec conversion'},
{value: OPERATION_VALUE.ANNULATION_ETATS_ADMINISTRATIFS, text: 'Annulation des états administratifs'},
{value: OPERATION_VALUE.EXECUTION_REQUETE_ANTS, text: 'Exécution d\'une requête ANTS'},
{value: OPERATION_VALUE.ANN_PROG_REQUETE_ANTS, text: 'Annulation d\'une programmation de requête ANTS'},
{value: OPERATION_VALUE.ENR_PROG_REQUETE_ANTS, text: 'Enregistrement d\'une programmation de requête ANTS'},
{value: OPERATION_VALUE.OUTREPASSER_VOL, text: 'Outrepasser : vol'},
{value: OPERATION_VALUE.OUTREPASSER_VIN_DOUBLON, text: 'Outrepasser : VIN en doublon'},
{value: OPERATION_VALUE.OUTREPASSER_VIN_NON_CONTROLE, text: 'Outrepasser : contrôle du VIN Indisponible'},
{value: OPERATION_VALUE.OUTREPASSER_OTC_INDISPONIBLE, text: 'Outrepasser : contrôle OTC indisponible'},
{value: OPERATION_VALUE.OUTREPASSER_CT_EXONERATION, text: 'Outrepasser : exonération du contrôle technique'},
{value: OPERATION_VALUE.OUTREPASSER_CT_EXEMPTION, text: 'Outrepasser : soumission au CT'},
{value: OPERATION_VALUE.OUTREPASSER_EXONERATION_TAXES, text: 'Outrepasser : exonération des taxes'},
{value: OPERATION_VALUE.OUTREPASSER_REFCNIT_RUBVARIABLES, text: 'Outrepasser : Saisie de rubriques variables du CNIT hors limites'},
{value: OPERATION_VALUE.OUTREPASSER_REFCNIT_MENTIONVARIABLE, text: 'Outrepasser : Mentions variables du CNIT absentes ou hors limites'},
{value: OPERATION_VALUE.BATCH_VEHICULES_IMPORTES, text: 'Fournir des fichiers de véhicules étrangers immatriculés en France'},
{value: OPERATION_VALUE.EDIT_ETAT_REGIE, text: 'Edition d\'un état de régie'},
]
