export const REPORT_TABS = {
  SYNTHESE: 'SYNTHESE',
  VEHICULE: 'VEHICULE',
  TITULAIRE_ET_TITRE: 'TITULAIRE_ET_TITRE',
  SITUATION_ADMINISTRATIVE: 'SITUATION_ADMINISTRATIVE',
  HISTORIQUE: 'HISTORIQUE',
  CONTROLES_TECHNIQUES: 'CONTROLES_TECHNIQUES',
  KILOMETRAGE: 'KILOMETRAGE',
}
