export const TYPE_IMMATRICULATION = {
  FNI: 'FNI',
  SIV: 'SIV',
}

export const OLD_IMMATRICULATION_TYPE = 'OLD'

export const TYPE_PERSONNE = {
  PARTICULIER: 'PARTICULIER',
  PRO: 'PRO',
}

export const TYPE_RAPPORT = {
  ACHETEUR: 'ACHETEUR',
  VENDEUR: 'VENDEUR',
}
