export const REPONSE_API_STRING_PAR_DEFAUT = 'NON_CONNU'
export const REPONSE_API_DATE_PAR_DEFAUT = 'NON_CONNU'
export const REPONSE_API_NUMBER_PAR_DEFAUT = -99
export const AFFICHAGE_STRING_PAR_DEFAUT = null
export const AFFICHAGE_DATE_PAR_DEFAUT = null
export const AFFICHAGE_NUMBER_PAR_DEFAUT = null
