export const structureOngletHistorique = () => {
  cy.get("div[id*='report-tab-content-4']")
    .should("have.class", "fr-tabs__panel fr-tabs__panel--selected")
    .find("div[class='fr-grid-row fr-grid-row--gutters']")
    .should('have.length', 1)
    .find("div[class='fr-col-12 fr-pb-3w']")
    .should('have.length', 1)
    .find("h3")
    .should('have.length', 1)
    .contains("Historique des opérations en France")
    .parent()
    .parent()
    .find("div[class='fr-col-2 fr-pb-2w fr-pt-0']")
    .should('have.length', 1)
    .contains("Date")
    .parent()
    .parent()
    .find("div[class='fr-col-10 fr-pb-2w fr-pt-0']")
    .should('have.length', 1)
    .contains("Opération")
    .parent()
    .parent()
    .find("div[class='fr-col-12 fr-col-md-2 fr-col-lg-2 fr-col-xl-2 fr-pb-0 fr-pt-0']")
    .should('have.length', 3)
    .parent()
    .find("div[class='fr-col-12 fr-col-md-10 fr-col-lg-10 fr-col-xl-10 fr-pb-2w fr-pt-0 fr-text--bleu']")
    .should('have.length', 3)
}

export const contenuOngletHistorique = () => {
  cy.get("div[id*='report-tab-content-4']")
    .find("div[class='fr-grid-row fr-grid-row--gutters']")
    .find("div[class='fr-col-12 fr-col-md-2 fr-col-lg-2 fr-col-xl-2 fr-pb-0 fr-pt-0']").eq(0)
    .contains("26/08/2022")
    .parent()
    .parent()
    .find("div[class='fr-col-12 fr-col-md-2 fr-col-lg-2 fr-col-xl-2 fr-pb-0 fr-pt-0']").eq(1)
    .contains("18/05/2015")
    .parent()
    .parent()
    .find("div[class='fr-col-12 fr-col-md-2 fr-col-lg-2 fr-col-xl-2 fr-pb-0 fr-pt-0']").eq(2)
    .contains("20/04/2009")
    .parent()
    .parent()
    .find("div[class='fr-col-12 fr-col-md-10 fr-col-lg-10 fr-col-xl-10 fr-pb-2w fr-pt-0 fr-text--bleu']").eq(0)
    .contains("Achat ou reprise par un professionnel")
    .parent()
    .parent()
    .find("div[class='fr-col-12 fr-col-md-10 fr-col-lg-10 fr-col-xl-10 fr-pb-2w fr-pt-0 fr-text--bleu']").eq(1)
    .contains("Duplicata de la carte grise")
    .parent()
    .parent()
    .find("div[class='fr-col-12 fr-col-md-10 fr-col-lg-10 fr-col-xl-10 fr-pb-2w fr-pt-0 fr-text--bleu']").eq(2)
    .contains("Première immatriculation d'un véhicule neuf")
}
