heat_template_version: 2013-05-23

description: Stack de déploiement de l'infrastructure HistoVec pour le développement.

parameters:
  key_name:
    type: string
    label: Name of keypair to assign to servers
    description: key_name=foo
  front_subnet_cidr:
    type: string
    default: "192.168.1.0/24"
  back_subnet_cidr:
    type: string
    default: "192.168.2.0/24"
  dns_nameservers:
    type: comma_delimited_list
    label: DNS nameservers
    description: dns_nameservers=8.8.8.8,8.8.4.4
  floatingip_network_name:
    type: string
    label: The Floating Network
    description: floatingip_network_name=public
  floatingip_id_bastion:
    type: string
    label: The Floating IP for Bastion NAT
    description: floatingip_id=public
  floatingip_id_front:
    type: string
    label: The Floating IP for front NAT
    description: floatingip_id=public

  bastion_flavor:
    type: string
    label: The flavor for bastion Instances
    description: flavor=small
  front_flavor:
    type: string
    label: The flavor for front Instances
    description: flavor=xsmall
    default: small
  back_flavor:
    type: string
    label: The flavor for back Instances
    description: flavor=xsmall
    default: small

  bastion_image:
    type: string
    label: The debian bastion_image based for Instances
    description: bastion_image=debian-8-latest
    default: debian-8-latest
  bastion_vol_size:
    type: number
    description: The size of the Cinder volume for instance
    default: 10
  bastion_vol_type:
    type: string
    description: The volume type of the Cinder volume for instance
    default: default
  front_image:
    type: string
    label: The debian front_image based for Instances
    description: front_image=debian-8-latest
    default: debian-8-latest
  front_vol_size:
    type: number
    description: The size of the Cinder volume for instance
    default: 10
  front_vol_type:
    type: string
    description: The volume type of the Cinder volume for instance
    default: default
  back_image:
    type: string
    label: The debian back_image based for Instances
    description: back_image=debian-8-latest
    default: debian-8-latest
  back_vol_size:
    type: number
    description: The size of the Cinder volume for instance
    default: 10
  back_vol_type:
    type: string
    description: The volume type of the Cinder volume for instance
    default: default
  artefact_url:
    type: string
    description: url to artefact storage
    default: default
  docker_image:
    type: string
    description: docker.deb for installation
    default: default
  docker_compose_image:
    type: string
    description: docker-compse.deb for installation
    default: default

resources:
  front_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: { network: { get_param: floatingip_network_name } }

# front network
  front_network:
    type: OS::Neutron::Net

  front_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: front_network }
      cidr: { get_param: front_subnet_cidr }
      dns_nameservers: { get_param: dns_nameservers }
      ip_version: 4

  front_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: front_router }
      subnet: { get_resource: front_subnet }

  front_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: front_network }
      security_groups:
        - { get_resource: front_node_securitygroup }
      fixed_ips:
        - subnet_id: { get_resource: front_subnet }

  bastion_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: front_network }
      security_groups:
        - { get_resource: front_node_securitygroup }
      fixed_ips:
        - subnet_id: { get_resource: front_subnet }

  front_node_securitygroup:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 22
          port_range_max: 22
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 80
          port_range_max: 80
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 443
          port_range_max: 443

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: floatingip_network_name }
      port_id: { get_resource: back_port }

  back_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: front_network }
      security_groups:
        - { get_resource: back_node_securitygroup }
      fixed_ips:
        - subnet_id: { get_resource: front_subnet }

  back_node_securitygroup:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 22
          port_range_max: 22
        # elastic
        - remote_ip_prefix:  { get_param: front_subnet_cidr }
          protocol: tcp
          port_range_min: 9200
          port_range_max: 9200
          direction: ingress


# bastion compute
  bastion_vol:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: bastion_vol_size }
      image: { get_param: bastion_image }
      volume_type: { get_param: bastion_vol_type }

  bastion:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: bastion_flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: bastion_port }
      block_device_mapping:
        - device_name: vda
          volume_id: { get_resource: bastion_vol }
          delete_on_termination: false
      user_data_format: RAW
      user_data:
        str_replace:
          template: { get_file: param/bastion_postconf.sh }
          params:
            $artefact_url: { get_param: artefact_url }
            $docker_image: { get_param: docker_image }
            $docker_compose_image: { get_param: docker_compose_image }

  bastion_lien_floatingip:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_param: floatingip_id_bastion }
      port_id: { get_resource: bastion_port }

# front compute
  front_vol:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: front_vol_size }
      image: { get_param: front_image }
      volume_type: { get_param: front_vol_type }

  front:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: front_flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: front_port }
      block_device_mapping:
        - device_name: vda
          volume_id: { get_resource: front_vol }
          delete_on_termination: false
      user_data_format: RAW
      user_data:
        str_replace:
          template: { get_file: param/front_postconf.sh }
          params:
            $artefact_url: { get_param: artefact_url }
            $docker_image: { get_param: docker_image }
            $docker_compose_image: { get_param: docker_compose_image }

  front_lien_floatingip:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_param: floatingip_id_front }
      port_id: { get_resource: front_port }

# back compute
  back_vol:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: back_vol_size }
      image: { get_param: back_image }
      volume_type: { get_param: back_vol_type }

  back:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: back_flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: back_port }
      block_device_mapping:
        - device_name: vda
          volume_id: { get_resource: back_vol }
          delete_on_termination: false
      user_data_format: RAW
      user_data:
        str_replace:
          template: { get_file: param/back_postconf.sh }
          params:
            $artefact_url: { get_param: artefact_url }
            $docker_image: { get_param: docker_image }
            $docker_compose_image: { get_param: docker_compose_image }
