// @unused: Enum qui n'est plus utilisé désormais
// Cela peut être une bonne idée de le garder car il permet de documenter les différents types de genre de véhicule

export const GENRE = {
	CAM: 'CAM',
	CL: 'CL',
	CTTE: 'CTTE',
	CYCL: 'CYCL',
	MAGA: 'MAGA',
	MIAR: 'MIAR',
	MTL: 'MTL',
	MTT1: 'MTT1',
	MTT2: 'MTT2',
	QM: 'QM',
	REA: 'REA',
	REM: 'REM',
	RESP: 'RESP',
	RETC: 'RETC',
	SRAT: 'SRAT',
	SREA: 'SREA',
	SREM: 'SREM',
	SRSP: 'SRSP',
	SRTC: 'SRTC',
	TCP: 'TCP',
	TM: 'TM',
	TRA: 'TRA',
	TRR: 'TRR',
	VASP: 'VASP',
	VP: 'VP',
	XX: 'XX',
}
