import routes from "../../../constants/urls.json";

context('Rapport acheteur vehicule cas simple - onglet synthese', () => {
  before(() => {
    cy.intercept('POST', '/public/v1/get_token', { statusCode: 200, fixture: 'token.json' })
    cy.intercept('GET', '/public/v1/report_by_code/**', { statusCode: 200, fixture: '/api/reponseRequeteApiCode200.json' })
    cy.intercept('PUT', '**/buyer/ok', { statusCode: 200 })
    cy.intercept('PUT', '**/synthesis', { statusCode: 200 })

    // redirection vers la page propriétaire
    cy.visit(routes.url_rapport_acheteur + '?key=b30514dd-f4e8-4036-a102-87d5ca365e66')
    cy.title().should('eq', 'HistoVec - Rapport acheteur')
    cy.wait(500)

    // Onlget Synthèse selectionné
    cy.get("div[class*='fr-tabs']")
      .find("ul[class*='fr-tabs__list']")
      .find("li[class*='fr-tabs__item']")
      .should('have.length', 7)
      .eq(0)
      .find("button[class*='fr-tabs__tab']")
      .should('have.attr', 'aria-selected', 'true')
      .contains("Synthèse")
  })
  it("Affichage de l'onglet synthese - structure", () => {
    // Titres
    cy.get("div[id*='report-tab-content-0']")
      .should("have.class", "fr-tabs__panel fr-tabs__panel--selected")
      .find("div[class*='fr-col-12 fr-pb-3w']")
      .should('have.length', 1)
      .find("h3")
      .contains("Résumé")

    cy.get("div[id*='report-tab-content-0']")
      .find("h4")
      .should('have.length', 4)
  })
  it("Affichage de l'onglet synthese - modèle", () => {
    // Modèle
    cy.get("div[id*='report-tab-content-0']")
      .find("div[class*='fr-col-12 fr-col-lg-6 fr-col-xl-6']")
      .should('have.length', 2)
      .eq(0)
      .find("h4")
      .eq(0)
      .contains("Modèle")
      .parent()
      .find("p")
      .should('have.length', 3)
      .eq(0)
      .should("have.class", "fr-text--bleu")
      .contains("RENAULT MODUS")
      .parent()
      .find("p")
      .eq(1)
      .contains("Puissance fiscale :")
      .find("span")
      .should("have.class", "fr-text--bleu")
      .contains("5 ch")
      .parent()
      .parent()
      .find("p")
      .eq(2)
      .contains("Calculez le montant de votre certificat d'immatriculation")
      .find("a")
      .contains("Accédez au simulateur de calcul")
  })
  it("Affichage de l'onglet synthese - Propriétaire actuel", () => {
    // Propriétaire actuel
    cy.get("div[id*='report-tab-content-0']")
      .find("div[class*='fr-col-12 fr-col-lg-6 fr-col-xl-6']")
      .should('have.length', 2)
      .eq(0)
      .find("h4")
      .eq(1)
      .contains("Propriétaire actuel")
      .parent()
      .find("p")
      .should('have.length', 1)
      .contains("depuis")
      .contains("Ce véhicule a déjà eu")
      .contains("titulaire(s), en l'achetant vous serez le")
      .find("span")
      .should('have.length', 4)
      .eq(0)
      .should("have.class", "fr-text--bleu")
      .contains("B******T M****L")
      .parent()
      .find("span")
      .eq(1)
      .should("have.class", "fr-text--bleu")
      .contains("10")
      .parent()
      .find("span")
      .eq(2)
      .should("have.class", "fr-text--bleu")
      .contains("1").parent()
      .find("span")
      .eq(3)
      .should("have.class", "fr-text--bleu")
      .contains("2")
      .parent()
      .find("sup")
      .should('have.length', 1)
      .should("have.class", "fr-text--bleu")
      .contains("nd")
  })
  it("Affichage de l'onglet synthese - Immatriculation", () => {
    // Immatriculation
    cy.get("div[id*='report-tab-content-0']")
      .find("div[class*='fr-col-12 fr-col-lg-6 fr-col-xl-6']")
      .should('have.length', 2)
      .eq(1)
      .find("h4")
      .eq(0)
      .contains("Immatriculation")
      .parent()
      .find("p")
      .should('have.length', 1)
      .contains("Première immatriculation le")
      .find("span")
      .should("have.class", "fr-text--bleu")
      .contains("12/07/2003")
  })
  it("Affichage de l'onglet synthese - Situation administrative", () => {
    // Situation administrative
    cy.get("div[id*='report-tab-content-0']")
      .find("div[class*='fr-col-12 fr-col-lg-6 fr-col-xl-6']")
      .should('have.length', 2)
      .eq(1)
      .find("h4")
      .eq(1)
      .contains("Situation administrative")
      .parent()
      .find("p")
      .should('have.length', 1)
      .contains("(gages, opposition, vol,...)")
      .find("span")
      .should('have.length', 2)
      .eq(0)
      .should("have.class", "fr-text--bleu")
      .find("svg")
      .should("have.class", "ov-icon")
      .parent()
      .parent()
      .find("span")
      .eq(1)
      .should("have.class", "fr-text--bleu")
      .contains("Rien à signaler")
  })
})
