import routes from "../../../constants/urls.json";

context('Rapport vehicule cas simple - onglet synthese', () => {
  before(() => {
    // redirection vers la page propriétaire
    cy.visit(routes.url_proprietaire)
    cy.title().should('eq', 'HistoVec - Propriétaire')

    // mock de la requete
    cy.intercept('POST', '/histovec/api/v1/report_by_data', { fixture: 'aucuneAnomalie.json' }).as('dataVehicule')

    // renseignement du formulaire
    cy.get("img[src*='/histovec/src/assets/img/plaque_siv.svg']")
      .click()
    cy.get("input[id*='form-siv-particulier-nom-naissance']")
      .should("exist")
      .type('nom')
    cy.get("input[id*='form-siv-particulier-prenom']")
      .should("exist")
      .type('prenom')
    cy.get("input[id*='form-siv-particulier-numero-immatriculation']")
      .should("exist")
      .type('AA-123-AA')
    cy.get("input[id*='form-siv-particulier-numero-formule']")
      .should("exist")
      .type('2013BZ80335')

    // validation du formulaire
    cy.get("button[id*='bouton-recherche']")
      .should('not.be.disabled')
      .click()

    // page de redirection
    cy.wait(500)
    cy.url().should('eq',  Cypress.config('baseUrl') + routes.url_rapport_vendeur)
    cy.title().should('eq', 'HistoVec - Rapport vendeur')

    // Onlget Synthèse selectionné
    cy.get("div[class*='fr-tabs']")
      .find("ul[class*='fr-tabs__list']")
      .find("li[class*='fr-tabs__item']")
      .should('have.length', 7)
      .eq(0)
      .find("button[class*='fr-tabs__tab']")
      .should('have.attr', 'aria-selected', 'true')
      .contains("Synthèse")
  })
  it("Affichage de l'onglet synthese - structure", () => {
    // Titres
    cy.get("div[id*='report-tab-content-0']")
      .should("have.class", "fr-tabs__panel fr-tabs__panel--selected")
      .find("div[class*='fr-col-12 fr-pb-3w']")
      .should('have.length', 1)
      .find("h5")
      .contains("Résumé")

    cy.get("div[id*='report-tab-content-0']")
      .find("h6")
      .should('have.length', 4)
  })
  it("Affichage de l'onglet synthese - modèle", () => {
    // Modèle
    cy.get("div[id*='report-tab-content-0']")
      .find("div[class*='fr-col-12 fr-col-lg-6 fr-col-xl-6']")
      .should('have.length', 2)
      .eq(0)
      .find("h6")
      .eq(0)
      .contains("Modèle")
      .parent()
      .find("p")
      .should('have.length', 2)
      .eq(0)
      .should("have.class", "fr-text--bleu")
      .contains("CITROEN C1")
      .parent()
      .find("p")
      .eq(1)
      .contains("Puissance fiscale :")
      .find("span")
      .should("have.class", "fr-text--bleu")
      .contains("4 ch")
  })
  it("Affichage de l'onglet synthese - Propriétaire actuel", () => {
    // Propriétaire actuel
    cy.get("div[id*='report-tab-content-0']")
      .find("div[class*='fr-col-12 fr-col-lg-6 fr-col-xl-6']")
      .should('have.length', 2)
      .eq(0)
      .find("h6")
      .eq(1)
      .contains("Propriétaire actuel")
      .parent()
      .find("p")
      .should('have.length', 1)
      .contains("depuis")
      .contains("Vous êtes le")
      .contains("titulaire de ce véhicule")
      .find("span")
      .should('have.length', 3)
      .eq(0)
      .should("have.class", "fr-text--bleu")
      .contains("H**** S******")
      .parent()
      .find("span")
      .eq(1)
      .should("have.class", "fr-text--bleu")
      .contains("12 ans")
      .parent()
      .find("span")
      .eq(2)
      .should("have.class", "fr-text--bleu")
      .contains("1")
      .parent()
      .find("sup")
      .should('have.length', 1)
      .should("have.class", "fr-text--bleu")
      .contains("er")
  })
  it("Affichage de l'onglet synthese - Immatriculation", () => {
    // Immatriculation
    cy.get("div[id*='report-tab-content-0']")
      .find("div[class*='fr-col-12 fr-col-lg-6 fr-col-xl-6']")
      .should('have.length', 2)
      .eq(1)
      .find("h6")
      .eq(0)
      .contains("Immatriculation")
      .parent()
      .find("p")
      .should('have.length', 1)
      .contains("Première immatriculation le")
      .find("span")
      .should("have.class", "fr-text--bleu")
      .contains("13/05/2009")
  })
  it("Affichage de l'onglet synthese - Situation administrative", () => {
    // Situation administrative
    cy.get("div[id*='report-tab-content-0']")
      .find("div[class*='fr-col-12 fr-col-lg-6 fr-col-xl-6']")
      .should('have.length', 2)
      .eq(1)
      .find("h6")
      .eq(1)
      .contains("Situation administrative")
      .parent()
      .find("p")
      .should('have.length', 1)
      .contains("(gages, opposition, vol,...)")
      .find("span")
      .should('have.length', 2)
      .eq(0)
      .should("have.class", "fr-text--bleu")
      .find("svg")
      .should("have.class", "ov-icon")
      .parent()
      .parent()
      .find("span")
      .eq(1)
      .should("have.class", "fr-text--bleu")
      .contains("Rien à signaler")
  })
})
