name: Docker Image CI

on:
  pull_request:
    branches:
      - dev

jobs:

  test-build:
    name: Run tests
    runs-on: ubuntu-latest

    env:
      DOCKER_COMPOSE_VERSION: 1.19.0

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.14.0
        uses: actions/setup-node@v1
        with:
          node-version: '12.14.0'
      - name: Test all (client and server)
        run: ./ci/run-tests.sh
